#!/bin/bash

echo `date`
echo "Wait for setup"
sleep 5

echo `date`
echo "Pulling Latest"
git fetch --all
git pull

cd Server

echo `date`
echo "BUILDING"
swift build -c release

echo `date`
echo "RUNNING"
.build/release/Run --port 8090
