source 'https://github.com/kevcodex/kevcodex-podspecs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'iOS-Client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-Client

  pod 'MiniNe', '1.2.1'
end
